version: "3.7"

services:

  frontend:
    image: frontend
    build: ./flask_frontend/
    ports:
      - target: 5000
        published: 80
        protocol: tcp
        mode: host
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_IP=${MYSQL_IP}
      - SECRET_KEY=${SECRET_KEY}

  prize:
    image: prize_service
    build: ./flask_prize/
    depends_on:
      - temperature
      - countries

  temperature:
    image: temperature_service
    build: ./flask_temperature_api/
    environment:
      - API_KEY=${API_KEY}

  countries:
    image: countries_service
    build: ./flask_countries/
    #ports:
    #  - target: 5000
    #    published: 5001
