apiVersion: apps/v1 # endpoint 
kind: Deployment # replica set
metadata:
  name: frontend
  labels: 
    app: frontend
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/{{PROJECT_ID}}/frontend_service:build-{{BUILD_NUMBER}}
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: countries
  labels:
    app: countries
spec:
  replicas: 2
  selector:
    matchLabels:
      app: countries
  template:
    metadata:
      labels:
        app: countries
    spec:
      containers:
      - name: countries
        image: gcr.io/{{PROJECT_ID}}/countries_service:build-{{BUILD_NUMBER}}
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: countries
spec:
  selector:
    app: countries
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP

---
apiVersion: apps/v1             
kind: Deployment
metadata:
  name: prize
  labels: 
    app: prize
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prize
  template:
    metadata:
      labels:
        app: prize
    spec: 
      containers:
      - name: prize
        image: gcr.io/{{PROJECT_ID}}/prize_service:build-{{BUILD_NUMBER}}
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
           
---
apiVersion: v1
kind: Service
metadata:
  name: prize
spec:
  selector:
    app: prize
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature
  labels: 
    app: temperature
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: temperature
  template:
    metadata:
      labels:
        app: temperature
    spec:
      containers:
      - name: temperature
        image: gcr.io/{{PROJECT_ID}}/temperature_service:build-{{BUILD_NUMBER}}
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
        env:
        - name: API_KEY
          value: {{API_KEY}}
 
---
apiVersion: v1
kind: Service
metadata:
  name: temperature
spec:
  selector:
    app: temperature
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP

